import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "../../../imports";
import "./globals.css";
import { CartProvider } from "@/states/providers";
import { useCart } from "@/states/hooks/useCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { totalItems } = useCart();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Navbar totalItems={totalItems} />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
